# Generated by Django 4.2.7 on 2024-01-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='post_image',
            new_name='image',
        ),
    ]
