# Generated by Django 4.2.7 on 2024-01-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postunlikemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikemodel',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.postmodel'),
        ),
        migrations.AlterField(
            model_name='postunlikemodel',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlikes', to='post.postmodel'),
        ),
    ]
